# Generated by Django 3.1.3 on 2020-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spampi', '0002_mail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
