# Generated by Django 3.1.3 on 2020-11-29 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spampi', '0003_auto_20201129_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
