# Generated by Django 3.1.3 on 2020-12-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spampi', '0006_auto_20201207_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='user',
        ),
    ]
