# Generated by Django 3.1.3 on 2020-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spampi', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='original_quota',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
